In [53]:
import numpy as np 
import pandas as pd

In [54]:

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [55]:
data = pd.read_csv('IMDB Dataset.csv')
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [56]:
data.shape

(50000, 2)

In [57]:
data['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [58]:
data['review'] = data['review'].str.lower()

In [59]:
data

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [60]:
import re 
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r"", text)

In [61]:
text = "<html><body><h1>Title</h1><p>This is a paragraph.</p></body></html>"
remove_html_tags(text)

'TitleThis is a paragraph.'

In [62]:
data['review'] = data['review'].apply(remove_html_tags)

In [63]:
data['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [64]:
import time
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [65]:
excule = string.punctuation

In [66]:
def remove_punctuation(text):
    for char in excule:
        text = text.replace(char, "")
    return text

In [67]:
text = 'String. With. Punctuation?'

In [68]:
start = time.time()
print(remove_punctuation(text))
time1 = time.time() - start
print(time1*50000)

String With Punctuation
11.861324310302734

In [69]:
def remove_punchuation_standard_method(text):
    return text.translate(str.maketrans('','', excule))

In [70]:
start = time.time()
remove_punchuation_standard_method(text)
time2 = time.time() - start
print(time2*50000)

4.9591064453125

In [80]:
chat_words = pd.read_csv('slang.txt', sep='=')
chat_words

        A3 Anytime, Anywhere, Anyplace
0     ADIH         Another Day In Hell
1      AFK          Away From Keyboard
2    AFAIK            As Far As I Know
3     ASAP         As Soon As Possible
4      ASL          Age, Sex, Location
..     ...                         ...
98     WTG                  Way To Go!
99     WUF         Where Are You From?
100    WYD             What You Doing?
101   WYWH          Wish You Were Here
102    ZZZ      Sleeping, Bored, Tired

[103 rows x 2 columns]

In [81]:
def chat_convo(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [82]:
chat_convo('TTYL, I will BRB. BTW, this is a test message')

'TTYL, I will BRB. BTW, this is a test message'

In [83]:
! pip install textblob

Defaulting to user installation because normal site-packages is not writeable
Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: nltk>=3.9 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from textblob) (3.9.3)
Requirement already satisfied: click in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (2026.2.28)
Requirement already satisfied: tqdm in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 624.3/624.3 kB 8.3 MB/s  0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.19.0

WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)
WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)
WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)

In [84]:
from textblob import TextBlob

In [86]:
incorrect_sentence = "Cenrtain condilition durrrings the procesc"
textblb = TextBlob(incorrect_sentence)
textblb.correct()

TextBlob("Certain condition durings the process")

In [87]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [88]:
remove_emoji("Hello 👋, how are you? 😊")

'Hello , how are you? '

In [92]:
! pip install emoji

Defaulting to user installation because normal site-packages is not writeable
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 608.4/608.4 kB 7.3 MB/s  0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)
WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)
WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)

In [93]:
import emoji
print(emoji.demojize("Hello 👋, how are you? 😊"))

Hello :waving_hand:, how are you? :smiling_face_with_smiling_eyes:

In [94]:
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [95]:
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [96]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

In [97]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [98]:
sent1 = 'I am going to visit delhi!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [99]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry? 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, \nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [ ]:
sent5 = 'I have a Ph.D in A.I'
word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [101]:
! pip install spacy

Defaulting to user installation because normal site-packages is not writeable
Collecting spacy
  Downloading spacy-3.8.11-cp314-cp314-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp314-cp314-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.12-cp314-cp314-win_amd64.whl.metadata (2.6 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.10-cp314-cp314-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.5.2-cp314-cp314-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.4.2 (from spacy)
  Downloading weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typer-slim<1.0.0,>=0.3.0 (from spacy)
  Downloading typer_slim-0.24.0-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from spacy) (2.4.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from spacy) (2.32.5)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Downloading pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Requirement already satisfied: jinja2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from spacy) (25.0)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading pydantic_core-2.41.5-cp314-cp314-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.3.3-cp314-cp314-win_amd64.whl.metadata (7.7 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Collecting typer>=0.24.0 (from typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading smart_open-7.5.1-py3-none-any.whl.metadata (24 kB)
Collecting wrapt (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy)
  Downloading wrapt-2.1.1-cp314-cp314-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: click>=8.2.1 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Collecting shellingham>=1.3.0 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from jinja2->spacy) (3.0.3)
Downloading spacy-3.8.11-cp314-cp314-win_amd64.whl (14.4 MB)
   ---------------------------------------- 0.0/14.4 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/14.4 MB 7.4 MB/s eta 0:00:02
   ---------- ----------------------------- 3.9/14.4 MB 8.7 MB/s eta 0:00:02
   ----------------- ---------------------- 6.3/14.4 MB 9.5 MB/s eta 0:00:01
   ---------------------- ----------------- 8.1/14.4 MB 9.3 MB/s eta 0:00:01
   ------------------------ --------------- 8.9/14.4 MB 7.9 MB/s eta 0:00:01
   -------------------------- ------------- 9.7/14.4 MB 7.2 MB/s eta 0:00:01
   ----------------------------- ---------- 10.5/14.4 MB 6.9 MB/s eta 0:00:01
   -------------------------------- ------- 11.5/14.4 MB 6.4 MB/s eta 0:00:01
   -------------------------------- ------- 11.8/14.4 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 12.1/14.4 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 12.3/14.4 MB 5.2 MB/s eta 0:00:01
   ---------------------------------- ----- 12.6/14.4 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 13.1/14.4 MB 4.7 MB/s eta 0:00:01
   ------------------------------------- -- 13.6/14.4 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 13.9/14.4 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 14.4/14.4 MB 4.1 MB/s  0:00:03
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.13-cp314-cp314-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp314-cp314-win_amd64.whl (26 kB)
Downloading preshed-3.0.12-cp314-cp314-win_amd64.whl (120 kB)
Downloading pydantic-2.12.5-py3-none-any.whl (463 kB)
Downloading pydantic_core-2.41.5-cp314-cp314-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 2.7 MB/s eta 0:00:01
   -------------------- ------------------- 1.0/2.0 MB 2.9 MB/s eta 0:00:01
   ------------------------------------ --- 1.8/2.0 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 2.2 MB/s  0:00:00
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.2-cp314-cp314-win_amd64.whl (658 kB)
   ---------------------------------------- 0.0/658.9 kB ? eta -:--:--
   ---------------------------------------- 658.9/658.9 kB 3.6 MB/s  0:00:00
Downloading thinc-8.3.10-cp314-cp314-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 3.7 MB/s  0:00:00
Downloading blis-1.3.3-cp314-cp314-win_amd64.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.3 MB 3.0 MB/s eta 0:00:02
   ------ --------------------------------- 1.0/6.3 MB 2.8 MB/s eta 0:00:02
   ----------- ---------------------------- 1.8/6.3 MB 2.9 MB/s eta 0:00:02
   -------------- ------------------------- 2.4/6.3 MB 2.9 MB/s eta 0:00:02
   ------------------- -------------------- 3.1/6.3 MB 3.0 MB/s eta 0:00:02
   --------------------- ------------------ 3.4/6.3 MB 2.7 MB/s eta 0:00:02
   ----------------------- ---------------- 3.7/6.3 MB 2.5 MB/s eta 0:00:02
   -------------------------- ------------- 4.2/6.3 MB 2.4 MB/s eta 0:00:01
   ----------------------------- ---------- 4.7/6.3 MB 2.4 MB/s eta 0:00:01
   --------------------------------- ------ 5.2/6.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 5.5/6.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  6.3/6.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 2.4 MB/s  0:00:02
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Downloading typer_slim-0.24.0-py3-none-any.whl (3.4 kB)
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.3-py3-none-any.whl (50 kB)
Downloading cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Downloading smart_open-7.5.1-py3-none-any.whl (64 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading wrapt-2.1.1-cp314-cp314-win_amd64.whl (60 kB)
Installing collected packages: wrapt, wasabi, typing-inspection, spacy-loggers, spacy-legacy, shellingham, pydantic-core, murmurhash, mdurl, cymem, cloudpathlib, catalogue, blis, annotated-types, annotated-doc, srsly, smart-open, pydantic, preshed, markdown-it-py, rich, confection, typer, thinc, typer-slim, weasel, spacy

   ----------------------------------------  0/27 [wrapt]
   - --------------------------------------  1/27 [wasabi]
   -- -------------------------------------  2/27 [typing-inspection]
   ---- -----------------------------------  3/27 [spacy-loggers]
   ----- ----------------------------------  4/27 [spacy-legacy]
   ----- ----------------------------------  4/27 [spacy-legacy]
   -------- -------------------------------  6/27 [pydantic-core]
   ---------- -----------------------------  7/27 [murmurhash]
   -------------- ------------------------- 10/27 [cloudpathlib]
   -------------- ------------------------- 10/27 [cloudpathlib]
   -------------- ------------------------- 10/27 [cloudpathlib]
   -------------- ------------------------- 10/27 [cloudpathlib]
   ----------------- ---------------------- 12/27 [blis]
   ------------------- -------------------- 13/27 [annotated-types]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ----------------------- ---------------- 16/27 [smart-open]
   ----------------------- ---------------- 16/27 [smart-open]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   -------------------------- ------------- 18/27 [preshed]
   -------------------------- ------------- 18/27 [preshed]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   -------------------------------- ------- 22/27 [typer]
   -------------------------------- ------- 22/27 [typer]
   -------------------------------- ------- 22/27 [typer]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]

WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)
WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)
WARNING: Ignoring invalid distribution ~ygments (C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages)