In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv("IMDB Dataset.csv")

In [3]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# Preprocessing

In [4]:
data['review'] = data['review'].str.lower()

In [5]:
data

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [6]:
import re
def remove_html_tag(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r"", text)

In [7]:
text = "<html><body><h1>Title</h1><p>This is a paragraph.</p></body></html>"
remove_html_tag(text)

'TitleThis is a paragraph.'

In [8]:
data['review'] = data['review'].apply(remove_html_tag)

In [9]:
data

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Finding total words in corpus

In [10]:
total_words = data['review'].str.split().str.len().sum()
print(total_words)

11355604

# Bag of words

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
cv = CountVectorizer()

In [13]:
model = cv.fit_transform(data['review'])

In [14]:
print(cv.vocabulary_)

{'one': 65523, 'of': 65112, 'the': 91976, 'other': 66197, 'reviewers': 77049, 'has': 41639, 'mentioned': 58782, 'that': 91940, 'after': 3161, 'watching': 100325, 'just': 49565, 'oz': 66906, 'episode': 30790, 'you': 103272, 'll': 54377, 'be': 9119, 'hooked': 43816, 'they': 92257, 'are': 6007, 'right': 77460, 'as': 6476, 'this': 92382, 'is': 47807, 'exactly': 31674, 'what': 100966, 'happened': 41335, 'with': 101882, 'me': 58196, 'first': 34293, 'thing': 92319, 'struck': 88349, 'about': 2024, 'was': 100232, 'its': 48027, 'brutality': 13402, 'and': 4779, 'unflinching': 96659, 'scenes': 80322, 'violence': 99209, 'which': 101079, 'set': 81920, 'in': 45768, 'from': 36211, 'word': 102248, 'go': 38629, 'trust': 94986, 'not': 64254, 'show': 83069, 'for': 35221, 'faint': 32636, 'hearted': 42079, 'or': 65827, 'timid': 92947, 'pulls': 73099, 'no': 63879, 'punches': 73146, 'regards': 75633, 'to': 93189, 'drugs': 28084, 'sex': 82017, 'hardcore': 41399, 'classic': 18056, 'use': 97867, 'it': 47965, 'called': 14551, 'nickname': 63546, 'given': 38305, 'oswald': 66181, 'maximum': 57742, 'security': 81283, 'state': 87282, 'penitentary': 68519, 'focuses': 35019, 'mainly': 56173, 'on': 65499, 'emerald': 29917, 'city': 17899, 'an': 4651, 'experimental': 32077, 'section': 81262, 'prison': 72104, 'where': 101053, 'all': 3935, 'cells': 16053, 'have': 41812, 'glass': 38385, 'fronts': 36238, 'face': 32510, 'inwards': 47606, 'so': 85134, 'privacy': 72120, 'high': 42896, 'agenda': 3219, 'em': 29801, 'home': 43596, 'many': 56815, 'aryans': 6470, 'muslims': 62088, 'gangstas': 37031, 'latinos': 52702, 'christians': 17476, 'italians': 47975, 'irish': 47689, 'more': 61068, 'scuffles': 81020, 'death': 23559, 'stares': 87184, 'dodgy': 27002, 'dealings': 23528, 'shady': 82151, 'agreements': 3329, 'never': 63338, 'far': 32933, 'away': 7561, 'would': 102407, 'say': 80092, 'main': 56159, 'appeal': 5648, 'due': 28250, 'fact': 32556, 'goes': 38752, 'shows': 83105, 'wouldn': 102411, 'dare': 23180, 'forget': 35365, 'pretty': 71946, 'pictures': 69576, 'painted': 67115, 'mainstream': 56183, 'audiences': 7161, 'charm': 16610, 'romance': 78111, 'doesn': 27022, 'mess': 58984, 'around': 6256, 'ever': 31508, 'saw': 80061, 'nasty': 62709, 'surreal': 89595, 'couldn': 21164, 'ready': 74827, 'but': 14086, 'watched': 100317, 'developed': 25224, 'taste': 90974, 'got': 39159, 'accustomed': 2334, 'levels': 53573, 'graphic': 39465, 'injustice': 46643, 'crooked': 22017, 'guards': 40183, 'who': 101261, 'sold': 85359, 'out': 66279, 'nickel': 63527, 'inmates': 46666, 'kill': 50737, 'order': 65892, 'get': 37833, 'well': 100737, 'mannered': 56719, 'middle': 59319, 'class': 18052, 'being': 9589, 'turned': 95301, 'into': 47379, 'bitches': 10752, 'their': 92050, 'lack': 52064, 'street': 88163, 'skills': 84089, 'experience': 32069, 'may': 57750, 'become': 9325, 'comfortable': 19173, 'uncomfortable': 96133, 'viewing': 99027, 'thats': 91957, 'if': 45127, 'can': 14748, 'touch': 93784, 'your': 103304, 'darker': 23205, 'side': 83379, 'wonderful': 102098, 'little': 54290, 'production': 72272, 'filming': 34013, 'technique': 91241, 'very': 98773, 'unassuming': 95974, 'old': 65374, 'time': 92890, 'bbc': 9092, 'fashion': 33084, 'gives': 38310, 'comforting': 19176, 'sometimes': 85506, 'discomforting': 26143, 'sense': 81634, 'realism': 74857, 'entire': 30615, 'piece': 69601, 'actors': 2537, 'extremely': 32354, 'chosen': 17418, 'michael': 59221, 'sheen': 82495, 'only': 65563, 'polari': 70627, 'he': 41946, 'voices': 99500, 'down': 27601, 'pat': 67913, 'too': 93488, 'truly': 94956, 'see': 81324, 'seamless': 81119, 'editing': 29097, 'guided': 40264, 'by': 14209, 'references': 75505, 'williams': 101554, 'diary': 25488, 'entries': 30666, 'worth': 102387, 'terrificly': 91718, 'written': 102554, 'performed': 68710, 'masterful': 57423, 'great': 39601, 'master': 57415, 'comedy': 19146, 'his': 43157, 'life': 53794, 'really': 74882, 'comes': 19161, 'things': 92330, 'fantasy': 32915, 'guard': 40170, 'rather': 74581, 'than': 91908, 'traditional': 94003, 'dream': 27846, 'techniques': 91242, 'remains': 76030, 'solid': 85395, 'then': 92107, 'disappears': 26036, 'plays': 70238, 'our': 66263, 'knowledge': 51266, 'senses': 81642, 'particularly': 67763, 'concerning': 19692, 'orton': 66094, 'halliwell': 40997, 'sets': 81937, 'flat': 34541, 'murals': 61965, 'decorating': 23807, 'every': 31545, 'surface': 89526, 'terribly': 91711, 'done': 27239, 'thought': 92482, 'way': 100441, 'spend': 86216, 'hot': 44104, 'summer': 89105, 'weekend': 100599, 'sitting': 83920, 'air': 3477, 'conditioned': 19795, 'theater': 91994, 'light': 53845, 'plot': 70358, 'simplistic': 83686, 'dialogue': 25442, 'witty': 101952, 'characters': 16528, 'likable': 53891, 'even': 31478, 'bread': 12711, 'suspected': 89676, 'serial': 81832, 'killer': 50750, 'while': 101092, 'some': 85469, 'disappointed': 26039, 'when': 101045, 'realize': 74871, 'match': 57486, 'point': 70559, 'risk': 77630, 'addiction': 2635, 'proof': 72483, 'woody': 102179, 'allen': 3969, 'still': 87691, 'fully': 36423, 'control': 20517, 'style': 88545, 'us': 97850, 'grown': 40043, 'love': 55025, 'most': 61292, 'laughed': 52758, 'at': 6877, 'comedies': 19143, 'years': 103030, 'decade': 23658, 've': 98444, 'been': 9410, 'impressed': 45686, 'scarlet': 80247, 'johanson': 49082, 'she': 82461, 'managed': 56503, 'tone': 93447, 'her': 42547, 'sexy': 82067, 'image': 45328, 'jumped': 49482, 'average': 7454, 'spirited': 86365, 'young': 103286, 'woman': 102068, 'crown': 22106, 'jewel': 48830, 'career': 15158, 'wittier': 101945, 'devil': 25267, 'wears': 100516, 'prada': 71443, 'interesting': 47143, 'superman': 89327, 'friends': 36099, 'basically': 8832, 'there': 92171, 'family': 32804, 'boy': 12414, 'jake': 48296, 'thinks': 92342, 'zombie': 103877, 'closet': 18414, 'parents': 67603, 'fighting': 33896, 'movie': 61492, 'slower': 84584, 'soap': 85144, 'opera': 65698, 'suddenly': 88900, 'decides': 23730, 'rambo': 74292, 'ok': 65307, 're': 74773, 'going': 38781, 'make': 56245, 'film': 33967, 'must': 62108, 'decide': 23725, 'thriller': 92556, 'drama': 27750, 'watchable': 100311, 'divorcing': 26822, 'arguing': 6068, 'like': 53893, 'real': 74844, 'we': 100479, 'totally': 93750, 'ruins': 78738, 'expected': 32033, 'boogeyman': 11924, 'similar': 83627, 'instead': 46905, 'meaningless': 58234, 'spots': 86621, '10': 59, 'playing': 70222, 'descent': 24878, 'dialogs': 25441, 'shots': 83031, 'ignore': 45178, 'them': 92078, 'petter': 69095, 'mattei': 57613, 'money': 60680, 'visually': 99354, 'stunning': 88477, 'watch': 100308, 'mr': 61606, 'offers': 65161, 'vivid': 99416, 'portrait': 71107, 'human': 44454, 'relations': 75908, 'seems': 81361, 'telling': 91440, 'power': 71373, 'success': 88833, 'do': 26894, 'people': 68586, 'different': 25631, 'situations': 83927, 'encounter': 30179, 'variation': 98340, 'arthur': 6389, 'schnitzler': 80528, 'play': 70191, 'same': 79474, 'theme': 92088, 'director': 25959, 'transfers': 94162, 'action': 2503, 'present': 71832, 'new': 63359, 'york': 103238, 'these': 92217, 'meet': 58431, 'connect': 20031, 'each': 28754, 'connected': 20032, 'another': 5208, 'next': 63451, 'person': 68887, 'know': 51257, 'previous': 71976, 'contact': 20318, 'stylishly': 88555, 'sophisticated': 85644, 'luxurious': 55484, 'look': 54751, 'taken': 90560, 'how': 44230, 'live': 54309, 'world': 102322, 'own': 66868, 'habitat': 40713, 'gets': 37849, 'souls': 85783, 'picture': 69574, 'stages': 86970, 'loneliness': 54681, 'inhabits': 46566, 'big': 10427, 'best': 10130, 'place': 70027, 'find': 34120, 'sincere': 83725, 'fulfillment': 36401, 'discerns': 26106, 'case': 15507, 'acting': 2493, 'good': 38933, 'under': 96253, 'direction': 25949, 'steve': 87612, 'buscemi': 14005, 'rosario': 78295, 'dawson': 23416, 'carol': 15319, 'kane': 49862, 'imperioli': 45557, 'adrian': 2863, 'grenier': 39720, 'rest': 76734, 'talented': 90600, 'cast': 15585, 'come': 19132, 'alive': 3924, 'wish': 101828, 'luck': 55203, 'await': 7536, 'anxiously': 5439, 'work': 102274, 'probably': 72171, 'my': 62214, 'favorite': 33232, 'story': 87951, 'selflessness': 81490, 'sacrifice': 79128, 'dedication': 23849, 'noble': 63893, 'cause': 15843, 'preachy': 71527, 'boring': 12130, 'despite': 25017, 'having': 41833, 'seen': 81364, '15': 308, 'times': 92921, 'last': 52640, '25': 872, 'paul': 68072, 'lukas': 55279, 'performance': 68705, 'brings': 13029, 'tears': 91204, 'eyes': 32422, 'bette': 10192, 'davis': 23389, 'few': 33742, 'sympathetic': 90177, 'roles': 78062, 'delight': 24262, 'kids': 50674, 'grandma': 39415, 'says': 80110, 'dressed': 27919, 'up': 97640, 'midgets': 59340, 'children': 17138, 'makes': 56255, 'fun': 36447, 'mother': 61322, 'slow': 84579, 'awakening': 7544, 'happening': 41337, 'roof': 78208, 'believable': 9665, 'startling': 87259, 'had': 40756, 'dozen': 27671, 'thumbs': 92659, 'sure': 89512, 'resurrection': 76808, 'dated': 23319, 'seahunt': 81103, 'series': 81839, 'tech': 91222, 'today': 93231, 'bring': 13023, 'back': 7831, 'kid': 50638, 'excitement': 31785, 'grew': 39738, 'black': 10835, 'white': 101186, 'tv': 95397, 'gunsmoke': 40465, 'were': 100807, 'hero': 42638, 'week': 100596, 'vote': 99619, 'comeback': 19133, 'sea': 81076, 'hunt': 44610, 'need': 63019, 'change': 16417, 'pace': 66959, 'water': 100345, 'adventure': 2916, 'oh': 65253, 'thank': 91919, 'outlet': 66364, 'view': 99018, 'viewpoints': 99032, 'movies': 61536, 'any': 5441, 'ole': 65398, 'believe': 9668, 'wanna': 100084, 'nice': 63496, 'read': 74805, 'plus': 70450, 'points': 70578, 'rhymes': 77247, 'lines': 54068, 'let': 53505, 'submit': 88680, 'leave': 53061, 'doubt': 27534, 'quit': 73833, 'lets': 53528, 'amazing': 4354, 'fresh': 36024, 'innovative': 46713, 'idea': 45015, '70': 1386, 'aired': 3491, 'brilliant': 13000, 'dropped': 28036, 'off': 65125, '1990': 649, 'funny': 36520, 'anymore': 5454, 'continued': 20426, 'decline': 23773, 'further': 36579, 'complete': 19484, 'waste': 100285, 'disgraceful': 26279, 'fallen': 32731, 'writing': 102551, 'painfully': 67103, 'bad': 7927, 'performances': 68706, 'almost': 4105, 'mildly': 59497, 'entertaining': 30582, 'respite': 76702, 'guest': 40233, 'hosts': 44103, 'hard': 41389, 'creator': 21682, 'hand': 41154, 'selected': 81470, 'original': 65995, 'also': 4174, 'chose': 17417, 'band': 8344, 'hacks': 40750, 'followed': 35103, 'recognize': 75158, 'such': 88860, 'brilliance': 12998, 'fit': 34355, 'replace': 76349, 'mediocrity': 58374, 'felt': 33502, 'give': 38301, 'stars': 87235, 'respect': 76683, 'made': 55881, 'huge': 44391, 'now': 64387, 'awful': 7580, 'encouraged': 30186, 'positive': 71166, 'comments': 19264, 'here': 42578, 'looking': 54760, 'forward': 35530, 'mistake': 60176, '950': 1547, 'films': 34042, 'worst': 102384, 'pacing': 66988, 'storyline': 87967, 'soundtrack': 85813, 'song': 85560, 'lame': 52277, 'country': 21252, 'tune': 95202, 'played': 70202, 'less': 53486, 'four': 35600, 'looks': 54767, 'cheap': 16745, 'extreme': 32351, 'rarely': 74510, 'happy': 41354, 'end': 30212, 'credits': 21709, 'prevents': 71968, 'giving': 38313, 'score': 80759, 'harvey': 41632, 'keitel': 50316, 'least': 53040, 'making': 56268, 'bit': 10748, 'effort': 29248, 'obsessives': 64891, 'gut': 40524, 'wrenching': 102491, 'laughter': 52771, 'will': 101532, 'hell': 42352, 'mom': 60613, 'liked': 53897, 'camp': 14696, 'phil': 69259, 'alien': 3879, 'those': 92471, 'quirky': 73826, 'humour': 44540, 'based': 8798, 'oddness': 65058, 'everything': 31559, 'actual': 2548, 'punchlines': 73151, 'odd': 65048, 'progressed': 72367, 'didn': 25584, 'jokes': 49137, 'low': 55075, 'budget': 13550, 'problem': 72190, 'itself': 48028, 'eventually': 31503, 'lost': 54911, 'interest': 47139, 'imagine': 45346, 'stoner': 87861, 'currently': 22513, 'partaking': 67728, 'something': 85500, 'better': 10193, 'try': 95007, 'brother': 13270, 'planet': 70090, '12': 220, 'came': 14636, 'recall': 75039, 'scariest': 80239, 'scene': 80312, 'bird': 10665, 'eating': 28895, 'men': 58679, 'dangling': 23092, 'helplessly': 42422, 'parachutes': 67463, 'horror': 43999, 'cheesy': 16868, 'saturday': 79951, 'afternoons': 3172, 'tired': 93056, 'formula': 35439, 'monster': 60825, 'type': 95567, 'usually': 97907, 'included': 45932, 'beautiful': 9261, 'might': 59398, 'daughter': 23342, 'professor': 72304, 'resolution': 76650, 'died': 25590, 'care': 15150, 'much': 61663, 'romantic': 78128, 'angle': 4979, 'year': 103018, 'predictable': 71624, 'plots': 70373, 'unintentional': 96886, 'humor': 44530, 'later': 52673, 'psycho': 72895, 'loved': 55035, 'star': 87158, 'janet': 48366, 'leigh': 53263, 'bumped': 13768, 'early': 28798, 'sat': 79865, 'took': 93494, 'notice': 64295, 'since': 83724, 'screenwriters': 80911, 'scary': 80265, 'possible': 71197, 'worn': 102352, 'rules': 78753, 'im': 45324, 'fan': 32817, 'boll': 11729, 'again': 3195, 'enjoyed': 30414, 'postal': 71203, 'maybe': 57760, 'apparently': 5638, 'bought': 12278, 'rights': 77477, 'cry': 22223, 'long': 54693, 'ago': 3294, 'before': 9469, 'game': 36952, 'finsished': 34211, 'killing': 50759, 'mercs': 58844, 'infiltrating': 46416, 'secret': 81242, 'research': 76546, 'labs': 52039, 'located': 54486, 'tropical': 94841, 'island': 47885, 'should': 83038, 'warned': 100173, 'schemed': 80400, 'together': 93271, 'along': 4123, 'legion': 53208, 'schmucks': 80514, 'feeling': 33397, 'loneley': 54678, 'invites': 47579, 'three': 92531, 'countrymen': 21255, 'players': 70206, 'names': 62526, 'til': 92848, 'schweiger': 80662, 'udo': 95690, 'kier': 50687, 'ralf': 74262, 'moeller': 60476, 'actually': 2554, 'selfs': 81493, 'biz': 10790, 'tale': 90597, 'jack': 48157, 'carver': 15480, 'yes': 103104, 'german': 37766, 'hail': 40860, 'bratwurst': 12650, 'dudes': 28238, 'however': 44246, 'tils': 92867, 'badass': 7936, 'complained': 19469, 'staying': 87351, 'true': 94932, 'whole': 101272, 'perspective': 68927, 'don': 27209, 'looked': 54754, 'kicking': 50633, 'beyond': 10267, 'demented': 24384, 'evil': 31593, 'mad': 55846, 'scientist': 80690, 'dr': 27688, 'krieger': 51643, 'genetically': 37584, 'mutated': 62137, 'soldiers': 85368, 'gms': 38605, 'performing': 68713, 'top': 93548, 'reminds': 76093, 'spoiler': 86475, 'vancouver': 98229, 'reason': 74939, 'palm': 67220, 'trees': 94465, 'rich': 77292, 'lumberjack': 55305, 'woods': 102163, 'haven': 41819, 'gone': 38908, 'started': 87250, 'mehehe': 58487, 'cannot': 14870, 'stay': 87347, 'bolls': 11740, 'shenanigans': 82579, 'delivers': 24296, 'meaning': 58228, 'suck': 88867, 'mentioning': 58783, 'imply': 45631, 'did': 25567, 'areas': 6013, 'boat': 11489, 'until': 97521, 'cromed': 21993, 'albino': 3720, 'squad': 86757, 'enters': 30571, 'laugh': 52752, 'reeks': 75459, 'scheisse': 80389, 'poop': 70906, 'simpletons': 83675, 'fa': 32466, 'take': 90551, 'wiff': 101440, 'ahead': 3373, 'btw': 13456, 'annoying': 5173, 'sidekick': 83389, 'shoot': 82947, 'him': 43030, 'minutes': 59850, 'screen': 80891, 'shakespeare': 82195, 'appreciate': 5753, 'trying': 95012, 'masses': 57389, 'why': 101344, 'ruin': 78730, 'because': 9293, 'scottish': 80799, 'certain': 16189, 'rev': 76966, 'bowdler': 12357, 'hence': 42472, 'bowdlerization': 12360, 'tried': 94628, 'victorian': 98924, 'era': 30883, 'words': 102261, 'improve': 45724, 'perfection': 68682, 'write': 102538, 'ten': 91517, 'text': 91854, 'english': 30362, 'composition': 19554, 'forte': 35486, 'keep': 50277, 'saying': 80101, 'does': 27016, 'cut': 22604, 'fantastic': 32906, 'prisoners': 72107, 'famous': 32815, 'george': 37709, 'clooney': 18401, 'roll': 78069, 'man': 56499, 'constant': 20235, 'sorrow': 85719, 'recommand': 75183, 'everybody': 31549, 'greetings': 39692, 'bart': 8751, 'kind': 50820, 'drawn': 27821, 'erotic': 30987, 'amateurish': 4334, 'unbelievable': 96023, 'bits': 10767, 'sort': 85724, 'school': 80554, 'project': 72388, 'rosanna': 78292, 'arquette': 6268, 'thinking': 92341, 'stock': 87793, 'bizarre': 10792, 'supposed': 89454, 'midwest': 59377, 'town': 93876, 'involved': 47594, 'lessons': 53495, 'learned': 53022, 'insights': 46824, 'stilted': 87706, 'quite': 73834, 'ridiculous': 77384, 'lots': 54931, 'skin': 84104, 'intrigues': 47421, 'videotaped': 98970, 'nonsense': 64075, 'bisexual': 10723, 'relationship': 75909, 'nowhere': 64395, 'heterosexual': 42756, 'encounters': 30183, 'absurd': 2123, 'dance': 23036, 'stereotyped': 87573, 'pass': 67831, 'million': 59595, 'miles': 59506, 'wasted': 100288, 'could': 21161, 'spent': 86224, 'starving': 87269, 'aids': 3427, 'africa': 3141, 'simply': 83688, 'remade': 76020, 'fails': 32631, 'capture': 15064, 'flavor': 34588, 'terror': 91734, '1963': 604, 'title': 93111, 'liam': 53660, 'neeson': 63041, 'excellent': 31739, 'always': 4267, 'holds': 43459, 'exception': 31754, 'owen': 66861, 'wilson': 101596, 'feel': 33393, 'character': 16503, 'luke': 55281, 'major': 56226, 'fault': 33198, 'version': 98749, 'strayed': 88139, 'shirley': 82811, 'jackson': 48195, 'attempts': 7053, 'grandiose': 39409, 'thrill': 92554, 'earlier': 28793, 'trade': 93989, 'snazzier': 84929, 'special': 86087, 'effects': 29223, 'enjoy': 30410, 'friction': 36067, 'older': 65379, 'horrible': 43977, 'wasn': 100268, 'continuous': 20433, 'minute': 59846, 'fight': 33890, 'chance': 16387, 'development': 25229, 'busy': 14081, 'running': 78818, 'sword': 90072, 'emotional': 30012, 'attachment': 7029, 'except': 31750, 'machine': 55752, 'wanted': 100094, 'destroy': 25062, 'blatantly': 11028, 'stolen': 87834, 'lotr': 54930, 'wars': 100216, 'matrix': 57596, 'examples': 31707, 'ghost': 37926, 'final': 34091, 'yoda': 103176, 'obee': 64749, 'vader': 98046, 'spider': 86267, 'beginning': 9516, 'frodo': 36189, 'attacked': 7035, 'return': 76937, 'kings': 50874, 'elijah': 29630, 'wood': 102128, 'victim': 98908, 'both': 12235, 'wait': 99889, 'hypnotizes': 44849, 'stings': 87729, 'wraps': 102467, 'uh': 95741, 'hello': 42381, 'vs': 99671, 'humans': 44487, 'terminator': 91676, 'someone': 85481, 'tell': 91433, 'nazi': 62890, 'juvenile': 49607, 'line': 54051, 'rushed': 78853, 'conclusion': 19726, 'adult': 2882, 'either': 29423, 'disappointment': 26043, 'save': 80025, 'remember': 76070, 'cinema': 17739, 'dark': 23198, 'places': 70036, 'nervous': 63235, '74': 1415, '75': 1422, 'dad': 22816, 'sister': 83888, 'newbury': 63369, 'berkshire': 10002, 'england': 30354, 'tigers': 92819, 'snow': 85072, 'appearance': 5654, 'grizzly': 39903, 'adams': 2600, 'actor': 2533, 'dan': 23030, 'haggery': 40820, 'think': 92334, 'shot': 83025, 'dies': 25607, 'anyone': 5456, 'knows': 51276, 'dvd': 28604, 'etc': 31283, 'please': 70272, 'fitness': 34359, 'club': 18472, 'shame': 82255, 'nearest': 62936, '20': 700, 'hear': 42044, 'others': 66202, 'against': 3199, 'stinkers': 87742, 'nominated': 63996, 'golden': 38811, 'globe': 38512, 'female': 33505, 'renaissance': 76153, 'painter': 67116, 'mangled': 56607, 'recognition': 75154, 'complaint': 19474, 'liberties': 53704, 'facts': 32576, 'perfectly': 68687, 'fine': 34129, 'accounts': 2300, 'artist': 6428, 'dishwater': 26322, 'dull': 28321, 'script': 80949, 'suppose': 89452, 'weren': 100814, 'enough': 30469, 'naked': 62496, 'factual': 32577, 'hurriedly': 44654, 'capped': 15006, 'summary': 89101, 'saved': 80026, 'ourselves': 66269, 'couple': 21269, 'hours': 44169, 'favored': 33228, 'brevity': 12871, 'die': 25588, 'sequels': 81757, 'surprise': 89586, '1990s': 651, 'glut': 38585, 'cashed': 15521, 'wrong': 102558, 'guy': 40552, 'concept': 19671, 'cliffhanger': 18277, 'mountain': 61420, 'rescue': 76539, 'sly': 84650, 'stop': 87894, 'stallone': 87059, 'nit': 63827, 'pickers': 69534, 'especially': 31144, 'expert': 32086, 'climbing': 18307, 'base': 8795, 'jumping': 49488, 'aviation': 7480, 'facial': 32534, 'expressions': 32224, 'full': 36407, 'excuses': 31847, 'dismiss': 26399, 'overblown': 66534, 'pile': 69691, 'junk': 49520, 'acted': 2487, 'horse': 44020, 'lovable': 55022, 'undeniably': 96251, 'romp': 78172, 'plenty': 70312, 'thrills': 92562, 'unintentionally': 96887, 'laughs': 52769, 'john': 49090, 'lithgows': 54258, 'sneery': 84953, 'evilness': 31603, 'tick': 92755, 'box': 12397, 'baddies': 7950, 'permanently': 68782, 'harasse

In [15]:
print(model)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6797178 stored elements and shape (50000, 104083)>
  Coords	Values
  (0, 65523)	1
  (0, 65112)	7
  (0, 91976)	16
  (0, 66197)	2
  (0, 77049)	1
  (0, 41639)	1
  (0, 58782)	1
  (0, 91940)	4
  (0, 3161)	1
  (0, 100325)	2
  (0, 49565)	2
  (0, 66906)	6
  (0, 30790)	2
  (0, 103272)	3
  (0, 54377)	3
  (0, 9119)	2
  (0, 43816)	1
  (0, 92257)	1
  (0, 6007)	2
  (0, 77460)	2
  (0, 6476)	4
  (0, 92382)	3
  (0, 47807)	9
  (0, 31674)	1
  (0, 100966)	2
  :	:
  (49999, 53158)	1
  (49999, 47085)	1
  (49999, 32025)	1
  (49999, 7502)	1
  (49999, 41424)	1
  (49999, 63033)	1
  (49999, 45935)	1
  (49999, 45601)	1
  (49999, 32877)	1
  (49999, 6361)	1
  (49999, 63755)	1
  (49999, 94473)	1
  (49999, 50947)	1
  (49999, 86471)	1
  (49999, 57925)	1
  (49999, 76243)	1
  (49999, 30791)	1
  (49999, 14315)	1
  (49999, 16445)	1
  (49999, 32038)	1
  (49999, 39001)	1
  (49999, 76236)	1
  (49999, 61694)	1
  (49999, 21850)	1
  (49999, 103246)	1

In [16]:
print(model[1].toarray())

[[0 0 0 ... 0 0 0]]

# Bag of word N gram

In [25]:
ngram = CountVectorizer(ngram_range=(1,4))

In [26]:
model_n_gram = ngram.fit_transform(data['review'])

In [19]:
model_n_gram

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10843172 stored elements and shape (50000, 9343224)>

In [28]:
print(ngram.get_feature_names_out())

['00' '00 01' '00 01 percent' ... 'כרמון is' 'כרמון is the'
 'כרמון is the president']

# TF-IDF

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tf = TfidfVectorizer()

In [23]:
tfidf = tf.fit_transform(data['review'])

In [24]:
tf.idf_

array([ 6.63801473,  5.70390616, 11.1266511 , ..., 11.1266511 ,
       11.1266511 , 11.1266511 ], shape=(104083,))

In [27]:
print(tf.get_feature_names_out())

['00' '000' '00000000000' ... 'żmijewski' 'יגאל' 'כרמון']